title: Son D. Nguyen
description: PhD Candidate in Mathematics, the University of Alabama, Tuscaloosa
site_title: '@hn17 - Nam H Nguyen'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
linkedin: namnguyenrice23 
github_username: hoainamnguyen94
email: sdnguyen1@crimson.ua.edu

# absolute or relative
profile_picture: assets/images/Son Nguyen.jpg

# Google Analytics ID
google_analytics: 
theme: jekyll-theme-cayman
