title: Nam H Nguyen
description: PhD Student in Statistics, Rice University
site_title: '@hn17 - Nam H Nguyen'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
linkedin: https://www.linkedin.com/in/namnguyenrice23/ 
github_username: hoainamnguyen94
email: hn17@rice.edu

# absolute or relative
profile_picture: assets/images/NamNguyen.jpg

# Google Analytics ID
google_analytics: 